from BlueScore import BleuScore, csvToList

referencesList=csvToList(10000,22,"corpus_good.csv")


#Candidate is the same of a one reference
print('BLEU score prueba 1-> {}'.format(BleuScore(referencesList,"""seriously how dumb can you be""".split())))

#Change one word for flowers
print('BLEU score prueba 2-> {}'.format(BleuScore(referencesList,"""corona has become something else flowers airport
has misunderstood everything now extorting money from""".split())))

#Change the same word virus
print('BLEU score prueba 3-> {}'.format(BleuScore(referencesList,"""corona has become something else virus airport
has misunderstood everything now extorting money from""".split())))    

#Change the candidate for random text
print('BLEU score prueba 4-> {}'.format(BleuScore(referencesList,"""asd""".split()))) 

#Change the candidate for the text with most score generated by the GAN 
print('BLEU score prueba 5-> {}'.format(BleuScore(referencesList,"""well we call the corona virus in the world is going on
""".split())))




